---
title: "Exploratory Data Visualization of Blight and Demolitions in Detroit"
author: "Lauren Li"
output: 
  html_document:
    code_folding: hide
---

```{r setup, include=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(ggrepel)
library(magrittr)

#read in csv
blight_tix <- read_csv(here('detroit_data','Blight_Violations.csv'))
side_lot_sales <- read_csv(here('detroit_data','Side_Lot_Sales.csv'))
past_demolitions <- read_csv(here('detroit_data', 'Detroit_Demolitions.csv'))
land_inv <- read_csv(here('detroit_data', 'Land_Bank_Inventory.csv'))
```


##Blight Violations




```{r, fig.width = 10}
blight_tix_graph <- blight_tix %>%
  filter(!is.na(`Fine Amount`)) %>%
  mutate(`Violation Description` = gsub("(.{31,}?)\\s", "\\1\n", `Violation Description`)) %>%
  mutate(`Violation Date` = as.Date(`Violation Date`,format = "%m/%d/%Y")) %>%
  mutate(year = `Violation Date`) %>%
  mutate(year = as.numeric(strftime(year, '%Y'))) %>%
  arrange(year) %>%
  filter(year >= 2006) %>%
  group_by(`Violation Description`, `Violation Code`) %>%
  summarize(count = n(), amount = mean(`Fine Amount`)) %>%
  arrange(amount) %>%
  filter(count > 10000)

blight_plot <- blight_tix_graph %>%
  ggplot(aes(x=factor(`Violation Description`, levels = blight_tix_graph$`Violation Description`), y=amount)) +
  geom_segment(aes(x=factor(`Violation Description`, levels = blight_tix_graph$`Violation Description`), xend=(factor(`Violation Description`, levels = blight_tix_graph$`Violation Description`)), y=0, yend=amount), color = 'gray', size=1.25) +
  geom_point(stat='identity', color='orange',size=3) + 
  geom_text(aes(label = round(amount)), vjust = -1, size=3, alpha=0.5) +
  theme_light() +
  coord_flip() +
  labs(title = 'High Penalties on Waste Pileup in Detroit', subtitle ='Most frequent blight violations since 2006', x = 'Violation Description', caption='Data Source: Detroit Open Data Portal') +
  scale_y_continuous(name = 'Average Fine Amount', breaks = c(0,250,500,750,1000,1250, 1500), labels = c('$0','$250','$500','$750','$1000', '$1250', '$1500'))

blight_plot
```


##Side Lot Sales


```{r, fig.width = 10}
side_lot_sales %<>% 
  mutate(`Closing Date` = as.Date(`Closing Date`,format = "%m/%d/%Y")) %>%
  mutate(year = `Closing Date`) %>%
  mutate(year = strftime(year, '%Y'))

neighborhoods_2016 <- side_lot_sales %>%
  group_by(`Neighborhood`, year) %>%
  summarize(count = n()) %>%
  filter(year=='2016') %>%
  filter(count > 50) %>%
  arrange(count)

neighborhoods_2017 <- side_lot_sales %>%
  group_by(`Neighborhood`, year) %>%
  summarize(count = n()) %>%
  filter(year=='2017') %>%
  filter(count > 50) %>%
  arrange(count)

neighborhoods_2018 <- side_lot_sales %>%
  group_by(`Neighborhood`, year) %>%
  summarize(count = n()) %>%
  filter(year=='2018') %>%
  filter(count > 50) %>%
  arrange(count)

all <- intersect(neighborhoods_2016$Neighborhood, neighborhoods_2017$Neighborhood)
neighborhoods <- intersect(all,neighborhoods_2018$Neighborhood)

#line graph: Side lot sales by (select) neighborhood and year
#next: look at this compared to inventory
lot_plot <- side_lot_sales %>%
  filter(`Neighborhood` %in% neighborhoods) %>%
  mutate(year = as.numeric(year)) %>%
  group_by(`Neighborhood`, year) %>%
  filter(year >= 2015) %>%
  filter(year != 2019) %>%
  summarize(count=n()) %>%
  ggplot(aes(x=year, y=count, group=`Neighborhood`)) + 
  geom_line(aes(color=`Neighborhood`)) + 
  theme_light() +
  labs(title = 'Claytown Has the Largest Number of Side Lot Sales', subtitle ='Eight Most Active Regions in the Side Lot Sales Program since 2015', x='Year', y='Number of Side Lots Sold', caption='Data Source: Detroit Open Data Portal')

lot_plot
```


##Detroit Land Bank Inventory

```{r, fig.width = 10}


for_sale <- land_inv %>%
  group_by(`Inventory Status`, `Council District`) %>%
  filter(`Inventory Status` == 'DLBA Owned Sidelot For Sale') %>%
  summarize(count = n())

for_sale_df <- data.frame('Sale' = for_sale$count, 'District' = for_sale$`Council District`) %>% mutate(District = paste('District', District))

owned <- land_inv %>%
  group_by(`Inventory Status`, `Council District`) %>%
  filter(`Inventory Status` == 'DLBA Owned Vacant Land') %>%
  summarize(count = n())

owned_df <- data.frame('Owned' = owned$count, 'District' = owned$`Council District`) %>% mutate(District = paste('District', District))

sale_owned <- merge(for_sale_df, owned_df, by='District')


district_owned_sale_plot <- sale_owned %>%
  ggplot(aes(x=Sale, y=Owned, group=District)) +
  geom_point(aes(color = District, size=Owned/Sale)) + 
  scale_size(range=c(3,10), breaks = c(1,1.5,2,2.5,3)) + #to manage size of bubbles 
  labs(title = 'District 5 (Downtown Detroit) Owns the Most Vacant Land in Proportion to Sidelots for Sale', subtitle ='Proportion of Owned Vacant Lots to Sidelots for Sale by District', y = 'Number of Owned Vacant Land', x= 'Number of Sidelots for Sale', caption='Data Source: Detroit Open Data Portal', size = 'Proportion of Owned Land \nto Lots For Sale') +
  theme_light()

district_owned_sale_plot
```


